export const defaultClients = [
  {
    id: 1,
    name: 'Bách Mỹ Group',
    logoUrl: '/image/featureclients/BackMyLogo.png',
    websiteUrl: 'https://bachmygroup.vn',
    description: 'Tập đoàn đa ngành hàng đầu Việt Nam',
    position: 0,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 2,
    name: 'DAVICOM',
    logoUrl: '/image/featureclients/davicom.jpg',
    websiteUrl: 'https://davicom.com.vn',
    description: 'CÔNG TY CP TRUYỀN THÔNG VÀ CÔNG NGHỆ ĐẠI VIỆT',
    position: 1,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 3,
    name: 'Kim Đông Dương',
    logoUrl: '/image/featureclients/kimdongduong.jpg',
    websiteUrl: 'https://kimdongduong.com.vn',
    description: 'Công ty TNHH Công nghệ và Truyền thông Kim Đông Dương',
    position: 2,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 4,
    name: 'Bidiphar',
    logoUrl: '/image/featureclients/BIDIPHAR.png',
    websiteUrl: 'https://bidiphar.com',
    description: 'CÔNG TY CỔ PHẦN DƯỢC TRANG BỊ THIẾT BỊ Y TẾ BÌNH ĐỊNH BIDIPHAR',
    position: 3,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 5,
    name: 'RedWok (Chảo đỏ)',
    logoUrl: '/image/featureclients/ChaoDo.png',
    websiteUrl: 'https://redwok.com.vn',
    description: 'CÔNG TY CỔ PHẦN ẨM THỰC CHẢO ĐỎ',
    position: 4,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 6,
    name: 'VietInfo',
    logoUrl: '/image/featureclients/VIETINFO.png',
    websiteUrl: 'https://news.vietinfo.tech',
    description: 'CÔNG TY CỔ PHẦN CÔNG NGHỆ VIETINFO',
    position: 5,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 7,
    name: 'Digibird',
    logoUrl: '/image/featureclients/Digibird.jpg',
    websiteUrl: 'https://digibird.co',
    description: 'CÔNG TY CỔ PHẦN DIGIBIRD',
    position: 6,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 8,
    name: 'SAPP',
    logoUrl: '/image/featureclients/SAPP.jpg',
    websiteUrl: 'https://sapp.edu.vn/',
    description: 'CÔNG TY CỔ PHẦN GIÁO DỤC SAPP',
    position: 7,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 9,
    name: 'VIETJET',
    logoUrl: '/image/featureclients/VIETJET.jpg',
    websiteUrl: 'https://www.vietjetair.com',
    description: 'CÔNG TY CỔ PHẦN HÀNG KHÔNG VIETJET',
    position: 8,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 10,
    name: 'PARISPHARM',
    logoUrl: '/image/featureclients/PARISPHARM.jpg',
    websiteUrl: 'http://www.parispharm.net',
    description: 'CÔNG TY CỔ PHẦN PARIS PHARM',
    position: 9,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 11,
    name: 'KEYCOM',
    logoUrl: '/image/featureclients/KEYCOM.jpg',
    websiteUrl: 'https://keycom.vn',
    description: 'CÔNG TY CỔ PHẦN THƯƠNG MẠI VÀ TRUYỀN THÔNG KEY',
    position: 10,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 12,
    name: 'FLAMINGO',
    logoUrl: '/image/featureclients/FLAMINGO.jpg',
    websiteUrl: 'https://flamingocorp.vn',
    description: 'CÔNG TY CỔ PHẦN TRUYỀN THÔNG SỐ FLAMINGO',
    position: 11,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 13,
    name: 'Ụt Ụt',
    logoUrl: '/image/featureclients/utut.jpg',
    websiteUrl: 'https://www.quanutut.com',
    description: 'CÔNG TY CỔ PHẦN ỤT ỤT',
    position: 12,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 14,
    name: 'VIET GROW',
    logoUrl: '/image/featureclients/VIETGROW.png',
    websiteUrl: 'http://megauni.vn',
    description: 'CÔNG TY CỔ PHẦN VIỆN PHÁT TRIỂN LÃNH ĐẠO',
    position: 13,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 15,
    name: 'WE FOOD',
    logoUrl: '/image/featureclients/WEFOOD.jpg',
    websiteUrl: 'https://wefoodjsc.com',
    description: 'CÔNG TY CỔ PHẦN WE FOOD',
    position: 14,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 16,
    name: 'CATHAY',
    logoUrl: '/image/featureclients/CATHAY.jpg',
    websiteUrl: 'https://www.cathay-ins.com.vn',
    description: 'CÔNG TY TNHH BẢO HIỂM PHI NHÂN THỌ CATHAY VIỆT NAM',
    position: 15,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 17,
    name: 'COEN BIO',
    logoUrl: '/image/featureclients/COEN.png',
    websiteUrl: 'https://coen-bio.com',
    description: 'CÔNG TY TNHH COEN-BIO',
    position: 16,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 18,
    name: 'GIGA NET',
    logoUrl: '/image/featureclients/GIGA-NET.png',
    websiteUrl: 'https://congnghegiganet.com',
    description: 'CÔNG TY TNHH CÔNG NGHỆ GIGA-NET',
    position: 17,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 19,
    name: 'XINGLILAI - VIỆT NAM',
    logoUrl: '/image/featureclients/XINGLILAI.jpg',
    websiteUrl: '',
    description: 'CÔNG TY TNHH CÔNG NGHIỆP XINGLILAI - VIỆT NAM',
    position: 18,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 20,
    name: 'FUDICO',
    logoUrl: '/image/featureclients/FUDICO.png',
    websiteUrl: 'https://fudico.com.vn',
    description: 'CÔNG TY TNHH FUDICO',
    position: 19,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 21,
    name: 'FUJI VIỆT NAM',
    logoUrl: '/image/featureclients/FUJI.jpg',
    websiteUrl: 'https://fujivietnam.com',
    description: 'CÔNG TY TNHH FUJI VIỆT NAM',
    position: 20,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 22,
    name: 'FUNCO',
    logoUrl: '/image/featureclients/FUNCO.jpg',
    websiteUrl: 'https://nikio.com.vn',
    description: 'CÔNG TY TNHH FUNCO',
    position: 21,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 23,
    name: 'GARMIN VIỆT NAM',
    logoUrl: '/image/featureclients/GARMIN.jpg',
    websiteUrl: 'https://www.garmin.com',
    description: 'CÔNG TY TNHH GARMIN VIỆT NAM',
    position: 22,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 24,
    name: 'GOC HEALTHY',
    logoUrl: '/image/featureclients/GOC-HEALTHY.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH GOC HEALTHY',
    position: 23,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 25,
    name: 'WONDER LAND',
    logoUrl: '/image/featureclients/WONDERLAND.png',
    websiteUrl: 'http://www.wonderlands.com.vn',
    description: 'CÔNG TY TNHH KINH DOANH TƯ VẤN ĐẦU TƯ WONDER LAND',
    position: 24,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 26,
    name: 'LANBENA',
    logoUrl: '/image/featureclients/LANBENA.png',
    websiteUrl: 'https://lanbena.com',
    description: 'CÔNG TY TNHH LANBENA',
    position: 25,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 27,
    name: 'LEMAR VIỆT NAM',
    logoUrl: '/image/featureclients/LEMAR.png',
    websiteUrl: 'https://lemar.com.vn',
    description: 'CÔNG TY TNHH LEMAR VIỆT NAM',
    position: 26,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 28,
    name: 'NOVO JAPAN',
    logoUrl: '/image/featureclients/NOVO-JAPAN.png',
    websiteUrl: 'https://novojapan.com.vn',
    description: 'CÔNG TY TNHH LIÊN DOANH DẦU NHỜN NOVO JAPAN',
    position: 27,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 29,
    name: 'HOLDING',
    logoUrl: '/image/featureclients/HOLDING.jpg',
    websiteUrl: '',
    description: 'CÔNG TY TNHH MOHODO HOLDING',
    position: 28,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 30,
    name: 'Thế Giới In Ấn',
    logoUrl: '/image/featureclients/TheGioiInAn.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH MỘT THÀNH VIÊN THẾ GIỚI IN ẤN',
    position: 29,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 31,
    name: 'BIO TECH',
    logoUrl: '/image/featureclients/BIO-TECH.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH MỸ PHẨM BIO TECH',
    position: 30,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 32,
    name: 'ON - GIFT VIỆT NAM',
    logoUrl: '/image/featureclients/ON-GIFT.jpg',
    websiteUrl: '',
    description: 'CÔNG TY TNHH ON - GIFT VIỆT NAM',
    position: 31,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 33,
    name: 'LTV',
    logoUrl: '/image/featureclients/LTV.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH PHẦN MỀM LTV',
    position: 32,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 34,
    name: 'VTEDCO',
    logoUrl: '/image/featureclients/VTEDCO.jpg',
    websiteUrl: '',
    description: 'CÔNG TY TNHH PHÁT TRIỂN ĐÀO TẠO GIÁO DỤC THÀNH CÔNG',
    position: 33,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 35,
    name: 'Huơng Việt',
    logoUrl: '/image/featureclients/HUONG-VIET.jpg',
    websiteUrl: '',
    description: 'CÔNG TY TNHH PHÁT TRIỂN HƯƠNG VIỆT',
    position: 34,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 36,
    name: 'INTERPRO TRANS',
    logoUrl: '/image/featureclients/INTERPRO-TRANS.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH PHIÊN DỊCH CHUYÊN NGHIỆP QUỐC TẾ',
    position: 35,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 37,
    name: 'THÀNH LỘC',
    logoUrl: '/image/featureclients/THANH-LOC.jpg',
    websiteUrl: '',
    description: 'CÔNG TY TNHH PHỤ GIA NHỰA THÀNH LỘC',
    position: 36,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 38,
    name: 'PHÚ HẢI TOÀN',
    logoUrl: '/image/featureclients/PHU-HAI-TOAN.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH PHÚ HẢI TOÀN',
    position: 37,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 39,
    name: 'IMMIGRATION LEGAL GROUP',
    logoUrl: '/image/featureclients/IMMIGRATION-LEGAL-GROUP.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH SOUTHWESTGATE IMMIGRATION LEGAL GROUP',
    position: 38,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 40,
    name: 'HTC SÀI GÒN',
    logoUrl: '/image/featureclients/HTC-SAI-GON.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH THƯƠNG MẠI HTC SÀI GÒN',
    position: 39,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 41,
    name: 'MILANO',
    logoUrl: '/image/featureclients/MILANO.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH THƯƠNG MẠI MILANO',
    position: 40,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 42,
    name: 'NỘI THẤT Ô TÔ QUANG MINH',
    logoUrl: '/image/featureclients/NHAT-OTOC.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH THƯƠNG MẠI XUẤT NHẬP KHẨU NỘI THẤT Ô TÔ QUANG MINH',
    position: 41,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 43,
    name: 'TI NO',
    logoUrl: '/image/featureclients/TI-NO.png',
    websiteUrl: '',
    description: 'CÔNG TY TNHH TI NO - CHI NHÁNH TI NO HÀ NỘI',
    position: 42,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 44,
    name: 'Nguyên Bảo Foods',
    logoUrl: '/image/featureclients/NGUYEN-BAO-FOODS.png',
    websiteUrl: '',
    description: 'Công ty TNHH Nguyên Bảo Foods',
    position: 43,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 45,
    name: 'Becamex Hotel Thu Dau Mot',
    logoUrl: '/image/featureclients/BECAMEX-HOTEL-THU-DAU-MOT.png',
    websiteUrl: '',
    description: 'Becamex Hotel Thu Dau Mot',
    position: 44,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 46,
    name: 'BIODERMA',
    logoUrl: '/image/featureclients/BIODERMA.png',
    websiteUrl: '',
    description: 'BIODERMA',
    position: 45,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 47,
    name: 'minthacare',
    logoUrl: '/image/featureclients/minthacare.png',
    websiteUrl: '',
    description: 'minthacare',
    position: 46,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 48,
    name: 'nuxe',
    logoUrl: '/image/featureclients/nuxe.png',
    websiteUrl: '',
    description: 'nuxe',
    position: 47,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 49,
    name: 'QUAN DOAN Q12',
    logoUrl: '/image/featureclients/QUAN-DOAN-Q12.jpg',
    websiteUrl: '',
    description: 'QUAN DOAN Q12',
    position: 48,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 50,
    name: 'mien-nam',
    logoUrl: '/image/featureclients/mien-nam.jpg',
    websiteUrl: '',
    description: 'mien-nam',
    position: 49,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  },
  {
    id: 51,
    name: 'final',
    logoUrl: '/image/featureclients/final.jpg',
    websiteUrl: '',
    description: 'final',
    position: 50,
    isActive: true,
    createdAt: '',
    updatedAt: ''
  }
];